### ISSUE TITLE
GTK4 AstalTray Popover Items are never disabled

### ISSUE THREAD

**Issue by Lodjuret** [Aylur/astal#312]
**Have you read through the documentation?**
- [x] [Astal docs](https://aylur.github.io/astal/)
- [x] [Library references](https://aylur.github.io/astal/guide/libraries/references)
- [x] [FAQ](https://aylur.github.io/astal/guide/typescript/faq)

**Describe what have you tried so far**
Can't get the correct disable state for the popover / menu items. All of them are always enabled.

I've tried this:

```
import { bind, Binding, Gio, GObject } from "astal";
import { Gtk } from "astal/gtk4";
import Tray from "gi://AstalTray";

const SYNC = GObject.BindingFlags.SYNC_CREATE;

export default function SysTray() {
  const tray = Tray.get_default();

  return (
    <box cssClasses={["SysTray"]}>
      {bind(tray, "items").as((items) =>
        items.map((item) => (
          <menubutton
            setup={(self) => {
              self.insert_action_group("dbusmenu", item.actionGroup);
            }}
            popover={Gtk.PopoverMenu.new_from_model(item.menu_model)}
            tooltip-markup={bind(item, "tooltip_markup")}
          />
        )),
      )}
    </box>
  );
}
```

and also this:

```
export default function SysTray() {
  const tray = Tray.get_default();

  return (
    <box cssClasses={["SysTray"]}>
      {bind(tray, "items").as((items) =>
        items.map((item) => renderTrayItem(item)),
      )}
    </box>
  );
}

function renderTrayItem(item: Tray.TrayItem) {
  const popover = Gtk.PopoverMenu.new_from_model(item.menu_model);
  const icon = new Gtk.Image();
  const button = new Gtk.MenuButton({
    popover,
    child: icon,
    cssClasses: ["items"],
  });

  item.bind_property("gicon", icon, "gicon", SYNC);
  popover.insert_action_group("dbusmenu", item.action_group);

  item.connect("notify::action-group", () => {
    popover.insert_action_group("dbusmenu", item.action_group);
  });

  return button;
}
```

**Describe your question**
How do i get the correct enable state for all popover items?

**Comment by kotontrion** [comment]
The menu is not created by AstalTray, so this is not an issue with this lib. I opened an issue for this in appmenu-glib-translator.

https://gitlab.com/vala-panel-project/vala-panel-appmenu/-/issues/398

**Comment by kotontrion** [comment]
should be fixed now in the appmenu-glib-translator lib.

**Comment by Lodjuret** [comment]
@kotontrion I'm using Nix with AGS and Astal so this appmenuglibtranslator is still not updated for me. I assume [lib/tray/default.nix](https://github.com/Aylur/astal/blob/main/lib/tray/default.nix) need to be updated for this fix to apply in my project? 

Should i create a new ticket for this? Thanks for the help before by the way.

**Comment by kotontrion** [comment]
There wasn't a new release until a few days ago. 
I updated it in #346

**Comment by Lodjuret** [comment]
Thanks, I used that branch and it works now. Missed that was the latest release for it. Thanks for the help!
